kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: kong
  namespace: default
spec:
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: proxy
            image: kong:3.6.1
            readinessProbe:
              initialDelaySeconds: 5
              periodSeconds: 60
            # env:
            #   - name: KONG_PLUGINS
            #     value: "bundled,serverless-functions"
## Create dataplane with service ClusterIP
    network:
      services:
        ingress:
          annotations: {}
          type: ClusterIP
## Create dataplane with service LoadBalancer
#    network:
#      services:
#        ingress:
#          annotations: {}
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
          - name: controller
            image: kong/kubernetes-ingress-controller:3.1.3
            env:
            - name: CONTROLLER_LOG_LEVEL
              value: debug